---
# This playbook deploys a simple standalone Tomcat 7 server.

- name: "Deploy the Tomcat server"
  hosts: tomcat-servers
  connection: local
  remote_user: root
  become: yes
  become_method: sudo

  environment:
    "{{proxy_env}}"

  roles:
    - selinux
    - tomcat
  tags
    - tomcat
